version: "2.2"

services:
  # Flink Job Manager
  jobmanager:
    container_name: FlinkJobManager
    image: flink:1.11.2-scala_2.11
    ports:
      - "8083:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
  # Flink Task Manager
  taskmanager:
    container_name: FlinkTaskManager
    image: flink:1.11.2-scala_2.11
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    links:
      - kafka
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 1

  nifi:
    hostname: nifi
    build: ./api/nifi/
    ports:
      - "8088:8080"
    links:
      - kafka
      - zookeeper
    environment:
      POLYGON_WS_URL: "wss://socket.polygon.io/stocks"
      POLYGON_TOKEN: ""
      # Check https://polygon.io/sockets for complete description of available subscriptions
      POLYGON_SUBSCRIPTIONS: "T.MSFT,T.AAPL,T.AMZN"

  zookeeper:
    image: zookeeper:3.4.9
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zookeeper:2888:3888

  kafka:
    image: confluentinc/cp-kafka:5.5.1
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  agent:
    build: .
    links:
      - kafka
    depends_on:
      - kafka
    environment:
      APCA_KEY: ""
      APCA_TOKEN: ""
      APCA_URL: "https://paper-api.alpaca.markets"
